databases:
  - name: app-mmse-db
    plan: free
    databaseName: suivi_heures
    user: suivi_heures_user

services:
  - type: web
    name: app-mmse-time
    env: python
    plan: free
    buildCommand: pip install -r suivi-heures-ot/requirements.txt
    startCommand: cd suivi-heures-ot && python main.py
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app-mmse-db
          property: connectionString
