services:
  - type: web
    name: app-mmse-time
    env: python
    plan: free
    buildCommand: pip install -r suivi-heures-ot/requirements.txt
    startCommand: cd suivi-heures-ot && python main.py
    autoDeploy: true
    envVars:
      - key: RENDER
        value: "true"
      - key: FORCE_RESET_DB
        value: "false"
      - key: RENDER_DEPLOY_VERSION
        value: "2"
