services:
  - type: web
    name: app-mmse-time
    env: python
    plan: free
    buildCommand: pip install -r suivi-heures-ot/requirements.txt
    startCommand: cd suivi-heures-ot && python main.py
    autoDeploy: true
    disk:
      name: app-mmse-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: APP_DATA_DIR
        value: /var/data
      - key: RENDER
        value: "true"
